config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :studys

  resources :steps

  resources :pages

  resources :relationships, only: [:create, :destroy]

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord

    belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
  
end

app/models/step.rb
class Step < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
end

app/models/study.rb
class Study < ApplicationRecord
belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :studys
         has_many :studys, dependent: :destroy 

         has_many :steps
         has_many :steps, dependent: :destroy 

         has_many :relationships
         has_many :followings, through: :relationships, source: :follow
         has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
         has_many :followers, through: :reverse_of_relationships, source: :user

         def follow(other_user)
          unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
      
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end

         validates :name, presence: true 
         validates :profile, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :nick])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def index
end

def new
    @page = Page.new
  end

  def show
    @page = Page.find_by(id: params[:id])
  end

  def create
    @page = Page.new(page_params)
    params[:page][:question] ? @page.question = params[:page][:question].join("") : false
    if @page.save
        flash[:notice] = "診断が完了しました"
        redirect_to page_path(@page.id)
    else
        redirect_to :action => "new"
    end
  end

private
  def page_params
      params.require(:page).permit(:id, question: [])
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

    before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_to @user
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to @user
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to @user
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to @user
    end
  end

  private
  def set_user
    @user = User.find(params[:follow_id])
  end

end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
    def index
        @steps = Step.all
    end
    
      def new
        @step = Step.new
      end
    
      def create
        step = Step.new(step_params)
        step.user_id = current_user.id
        if step.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
    

    
      def edit
        @step = Step.find(params[:id])
      end
    
      def update
        step = Step.find(params[:id])
        if step.update(step_params)
          redirect_to :action => "show", :id => step.id
        else
          redirect_to :action => "new"
        end
      end
    
      def destroy
        step = Step.find(params[:id])
        step.destroy
        redirect_to action: :index
      end
    
      private
      def step_params
        params.require(:step).permit(:body_second, :book, :image, :star, :tipe_second)
      end
end

app/controllers/studys_controller.rb
class StudysController < ApplicationController

def index
    @studys = Study.all
end

  def new
    @study = Study.new
  end

  def create
    study = Study.new(study_params)
    study.user_id = current_user.id
    if study.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

 

  def edit
    @study = Study.find(params[:id])
  end

  def update
    study = Study.find(params[:id])
    if study.update(study_params)
      redirect_to :action => "show", :id => study.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    study = Study.find(params[:id])
    study.destroy
    redirect_to action: :index
  end

  private
  def study_params
    params.require(:study).permit(:body, :learn, :tipe)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def index
      @users = User.all
      @user = User.find(current_user.id)
    end
    
    def show
      @user = User.find(params[:id])
      @following = @user.followings
      @follower = @user.followers
      render template: "relationships/_follow_button"
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          percent = calPercent.round
          return percent.to_s
        else
          return 0
        end
      end
end

app/helpers/studys_helper.rb
module StudysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Study</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" >
  <div class="container-fluid">
    <a class="navbar-brand" href="/pages">ホーム</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/steps">おすすめの書籍を紹介</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" href="/studys">勉強時間を記録</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" href="/users">ユーザー一覧</a>
        </li>

         <li class="nav-item">
          <a class="nav-link active" href="/users/sign_up">新規登録</a>
        </li>
        
      </ul>
      
    </div>
  </div>
</nav>


    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
  <style>
  body{
    background-color: #f2f4f7;
  }
  .card{
    background-color: skyblue;
 
  }
  </style>
</html>

app/views/pages/index.html.erb
<h1>💰投資学習コミュニティ💰</h1>
<%= link_to "診断を始める", new_page_path, class:"btn btn-outline-warning"%>
<% if user_signed_in? %>
    <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <%= link_to "マイページへ", user_path(current_user.id) ,class: "btn btn-outline-primary" %>
<% end %>

app/views/pages/new.html.erb
<%= form_for(@page, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="container-sindan">
        <h3>下の3つの質問に回答してください</h3>
        <div class="row">
            <div class="col-12">
                <p>質問１ お金を稼ぐにあたって</p>
            </div>
            <div class="col-sm-6 card">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>高リスクだとしても一攫千金を狙っていきたい</p>
            </div>
            <div class="col-sm-6 card">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>低リスクで確実にお金を稼ぎたい</p>
            </div>

            <div class="col-12">
                <p>質問２ あなたが最終的に受験しようと思った大学は？</p>
            </div>
            <div class="col-sm-6 card">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>D判定だけど第一志望の大学</p>
            </div>
            <div class="col-sm-6 card">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>B判定だけど第4志望の大学</p>
            </div>

            <div class="col-12">
                <p>質問３ あまり投資に時間を割くことができない。または割きたくない。</p>
            </div>
            <div class="col-sm-6 card">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>その通りである</p>
            </div>
            <div class="col-sm-6 card">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>時間を割くことができる。また割きたい。</p>
            </div>

        </div>
    </div>

    <div class="sindanbotan">
        <%= f.submit "送信",class: "btn btn-primary"%>
    </div>
<% end %>

app/views/pages/show.html.erb
<div class="intoro">
    <h2>診断結果</h2>
    <p class="yourType">あなたの投資タイプは！？</p>
</div>

<div class="type-container">
    <div class="typeSecond-container">
        <% if @page.question == "111" %>
            <div class="card">
                <h3>ハイリスク・ハイリターンタイプ！</h3>
                <img src="https://github.com/benesse-hackson-2022/fin-study-col/blob/master/app/views/images/high.png?raw=true" class="rounded mx-auto d-block">
                <p>投資が順調に進んでいる時には大きな利益を生むことができ、不調に陥ると一気に０になってしまう可能性が高い投資タイプ！</p>
                <p>短期で大きな利益を生むことができて一気に有名資産家に成り上がれるかも？</p>
                <p>株式投資やFXがおすすめ！</p>
                <%= link_to "さあ学習を始めよう！", pages_path, class: "btn btn-primary"%>
            </div>

        <% elsif @page.question == "112" %>
            <div class="card">
                <h3>ハイリスク・ハイリターンタイプ！</h3>
                <img src="https://github.com/benesse-hackson-2022/fin-study-col/blob/master/app/views/images/high.png?raw=true" class="rounded mx-auto d-block">
                <p>投資が順調に進んでいる時には大きな利益を生むことができ、不調に陥ると一気に０になってしまう可能性が高い投資タイプ！</p>
                <p>短期で大きな利益を生むことができて一気に有名資産家に成り上がれるかも？</p>
                <p>株式投資やFXがおすすめ！</p>
                <%= link_to "さあ学習を始めよう！", pages_path, class: "btn btn-primary"%>
            </div>

        <% elsif @page.question == "121" %>
            <div class="card">
                <h3>ミドルリスク・ミドルリターンタイプ！</h3>
                <img src="https://github.com/benesse-hackson-2022/fin-study-col/blob/master/app/views/images/hudou.png?raw=true" class="rounded mx-auto d-block">
                <p>それなりにリスクはあるものの、投資金額が0になる可能性は低めです！</p>
                <p>利益もほどほどに見込めます！短期決戦にはあまり向いていません！</p>
                <p>不動産投資がおすすめ！</p>
                <%= link_to "さあ学習を始めよう！", pages_path, class: "btn btn-primary"%>
            </div>

        <% elsif @page.question == "212" %>
            <div class="card">
                <h3>ミドルリスク・ミドルリターンタイプ！</h3>
                <img src="https://github.com/benesse-hackson-2022/fin-study-col/blob/master/app/views/images/hudou.png?raw=true" class="rounded mx-auto d-block">
                <p>それなりにリスクはあるものの、投資金額が0になる可能性は低めです！</p>
                <p>利益もほどほどに見込めます！短期決戦にはあまり向いていません！</p>
                <p>不動産投資がおすすめ！</p>
                <%= link_to "さあ学習を始めよう！", pages_path, class: "btn btn-primary"%>
            </div>

        <% elsif @page.question == "122" %>
            <div class="card">
                <h3>ミドルリスク・ミドルリターンタイプ！</h3>
                <img src="https://github.com/benesse-hackson-2022/fin-study-col/blob/master/app/views/images/hudou.png?raw=true" class="rounded mx-auto d-block">
                <p>それなりにリスクはあるものの、投資金額が0になる可能性は低めです！</p>
                <p>利益もほどほどに見込めます！短期決戦にはあまり向いていません！</p>
                <p>不動産投資がおすすめ！</p>
                <%= link_to "さあ学習を始めよう！", pages_path, class: "btn btn-primary"%>
            </div>

        <% elsif @page.question == "211" %>
            <div class="card">
                <h3>ミドルリスク・ミドルリターンタイプ！</h3>
                <img src="https://github.com/benesse-hackson-2022/fin-study-col/blob/master/app/views/images/hudou.png?raw=true" class="rounded mx-auto d-block">
                <p>それなりにリスクはあるものの、投資金額が0になる可能性は低めです！</p>
                <p>利益もほどほどに見込めます！短期決戦にはあまり向いていません！</p>
                <p>不動産投資がおすすめ！</p>
                <%= link_to "さあ学習を始めよう！", pages_path, class: "btn btn-primary"%>
            </div>

        <% elsif @page.question == "221" %>
            <div class="card">
                <h3>ローリスク・ローリターンタイプ！</h3>
                <img src="https://github.com/benesse-hackson-2022/fin-study-col/blob/master/app/views/images/raw.png?raw=true" class="rounded mx-auto d-block">
                <p>大きな利益はあまり期待できませんが、金額が全てなくなってしまうようなリスクはとても低いです！</p>
                <p>堅実に資産を形成していきたい人におすすめです！</p>
                <p>投資信託がおすすめ！</p>
                <%= link_to "さあ学習を始めよう！", pages_path, class: "btn btn-primary"%>
            </div>

        <% elsif @page.question == "222" %>
            <div class="card">
                <h3>ローリスク・ローリターンタイプ！</h3>
                <img src="https://github.com/benesse-hackson-2022/fin-study-col/blob/master/app/views/images/raw.png?raw=true" class="rounded mx-auto d-block">
                <p>大きな利益はあまり期待できませんが、金額が全てなくなってしまうようなリスクはとても低いです！</p>
                <p>堅実に資産を形成していきたい人におすすめです！</p>
                <p>投資信託がおすすめ！</p>
                <%= link_to "さあ学習を始めよう！", pages_path, class: "btn btn-primary"%>
            </div>
        <% end %>
    </div>
</div>

<style>

.rounded mx-auto d-block{
    width: 40%;
}
.intoro{
     text-align: center;
}
.type-container{
    text-align: center;
}
.card{
    background-color: #f2f4f7;
}
</style>

app/views/relationships/_follow_button.html.erb
<% unless current_user == @user %>
    <% if current_user.following?(@user) %>
        <%= form_for(current_user.relationships.find_by(follow_id: @user.id), html: { method: :delete }) do |f| %>
        <%= hidden_field_tag :follow_id, @user.id %>
        <p><%= @user.nick %></p>
        <%= f.submit 'フォローを解除する', class: 'btn btn-danger btn-block' %>
        <% end %>
    <% else %>
        <%= form_for(current_user.relationships.build) do |f| %>
        <%= hidden_field_tag :follow_id, @user.id %>
        <p><%= @user.nick %></p>
        <%= f.submit 'フォローする', class: 'btn btn-primary btn-block' %>
        <% end %>
    <% end %>
<% end %>

<% if current_user == @user %>

<h1>マイページ</h1>
<p>名前 : <%= @user.name %></p>
<p>ニックネーム : <%= @user.nick %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

  <%= link_to "編集する", edit_user_registration_path, class:"btn btn-outline-success" %>

<%= link_to "記録一覧に戻る", pages_path,class:"btn btn-outline-success" %>

<br><br>
  <h3>フォローされているユーザー</h3>
  <% @follower.each do |u| %>
      <%= link_to u.nick, user_path(u.id),class:"btn btn-outline-primary" %>
  <% end %>

<br><br>
  <h3>フォローしているユーザー</h3>
  <% @following.each do |u| %>
      <%= link_to u.nick, user_path(u.id) ,class:"btn btn-outline-primary"%>
  <% end %>

  <h3>投稿した書籍一覧</h3>
<% @user.steps.each do |t| %>
  <%= t.book %>
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
<% end %>

<% end %>

app/views/steps/index.html.erb
<h1>おすすめの参考書コーナー</h1>
<h3>参考書一覧</h3>
<%= link_to "書籍を登録しよう！", new_step_path , class: "btn btn-primary"%>

<div class="container">
    <div class="row">
    <% @steps.each do |t| %>
        <div class="col-sm-4" >
            <div class="card">
                <h2><%= t.user.nick %> </h2>
                <%= t.book %> <br>
                #<%= t.tipe_second %> <br>
                <%= t.body_second %> <br>
                <%= image_tag t.image_url, size: "250x200" if t.image? %>
                <% if user_signed_in? && current_user.id == t.user_id %>  
                <%= button_to "削除する",step_path(t.id), method: :delete %>
                <% end %>
            </div>
        </div>
    <% end %>
    </div>
</div>

<style>
.colo-sm-4.card{
    background-color: #skyblue;
}

</style>

app/views/steps/new.html.erb
<h1>おすすめの書籍を紹介！</h1>
<h3>書籍を登録する！</h3>
<%= form_for @step, url: steps_path do |f| %>
    <div class="field">
        <%= f.label :書名を入力 %> <br>
        <%= f.text_field :book, class: "form-control", required:true %>
        <br>
        <%= f.label :ジャンル %> <br><%= f.select :tipe_second , [["株式", "株式"], ["投資信託", "投資信託"], ["不動産", "不動産"], ["FX", "FX"], ["その他", "その他"]], include_blank: "ジャンル選択", required:true %>
        <br><br>
    <div class="field">
        <%= f.label :書籍の画像 %>
        <br>
        <%= f.file_field :image %>
     </div>
        <br>
        <%= f.label :閲覧または読んだ感想 %> <br><%= f.text_area :body_second, :size => 140, class: "form-control", required:true %>
        <br>
    </div>
<%= f.submit "記録する" , class:"btn btn-outline-danger"%>
<% end %>
<%= link_to "トップページに戻る", steps_path ,class: "btn btn-primary"%>

<style>
.form-control{
    width: 20%;
}
</style>

app/views/studys/index.html.erb
<h1>勉強時間記録ページ</h1>
<h3>Tweet一覧</h3>
<%= link_to "勉強時間を記録する", new_study_path, class: "btn btn-primary" %>
<div class="container">
  <div class="row">
    <% @studys.each do |t| %>
      <div class="col-sm-4" >
        <div class="card">
          <h3><%= t.user.nick %></h3>
          <%= t.tipe %> 
          <br>
          <%= t.body %>分<br>
          <%= t.learn %> <br>
          <% if user_signed_in? && current_user.id == t.user_id %> 
            <%= button_to "削除する",study_path(t.id), method: :delete %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/studys/new.html.erb
<h1>勉強時間記録ページ</h1>
<h3>勉強時間を記録する</h3>
<%= form_for @study, url: studys_path do |f| %>
<div class="field">
  <%= f.label :種類 %> <br><%= f.select :tipe , [["株式", "株式"], ["投資信託", "投資信託"], ["不動産", "不動産"], ["FX", "FX"], ["その他", "その他"]], include_blank: "選択して下さい", required:true %>
  <br>
  <%= f.label :勉強時間を入力（分） %> <br><%= f.number_field :body, :size => 140, required:true %>
  <br>
 <%= f.label :内容を入力 %> <br><%= f.text_area :learn, :size => 140, required:true %>
</div>
<%= f.submit "記録する", class:"btn btn-outline-danger" %> <% end %> <%= link_to "トップページに戻る", studys_path, class: "btn btn-primary"%>

app/views/users/index.html.erb
<h1><%= link_to "トップに戻る", pages_path, class:"btn btn-outline-primary"%></h1>

<h4>ログインしているユーザー</h4>
<p><%= @user.nick %></p>


<h4>ユーザー情報</h4>
<% @users.each do |u| %>
    <%= link_to u.nick, user_path(u.id),class:"btn btn-outline-primary" %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>